In [2]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split

<code>Simplest Linear Regression Implementation</code>

In [3]:

df = pd.read_csv('./Data/simple_linear_regression_data.csv')
X = df.iloc[:, 1].values.reshape(-1, 1)
y = df.iloc[:, 0].values
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [4]:

class S_LR():
  def __init__(self):
    self.m = None
    self.b = None
  def fit(self,X_train,y_train):
    num = 0
    den = 0
    for i in range(X_train.shape[0]):

      num += (((X_train[i] - X_train.mean())*(y_train[i] - y_train.mean())))
      den += (((X_train[i] - X_train.mean())*(X_train[i] - X_train.mean())))
    
      self.m = num/den
      self.b = y_train.mean() - self.m * X_train.mean()
  def predict(self,X_test):
    return self.m * X_test + self.b
  
lr = S_LR()
lr.fit(X_train, y_train)
lr.predict(X_test)

array([[3.27226494],
       [3.14764285],
       [2.39991033],
       [3.62536085],
       [4.26924163],
       [3.39688702],
       [5.97241015],
       [3.52150911],
       [9.42028788],
       [8.7764071 ],
       [9.66953206]])

In [5]:
lr.m.item(),lr.b.item()

(2.0770347788051216, -10.602327384584253)

In [6]:
from sklearn.linear_model import LinearRegression
sk = LinearRegression()
sk.fit(X_train, y_train)
sk.predict(X_test)

array([3.27226494, 3.14764285, 2.39991033, 3.62536085, 4.26924163,
       3.39688702, 5.97241015, 3.52150911, 9.42028788, 8.7764071 ,
       9.66953206])

In [7]:
sk.coef_.item(), sk.intercept_.item()

(2.0770347788051198, -10.602327384584239)

<code>Multiple Linear Regression Implementation</code>

In [8]:
df = pd.read_csv("./Data/multiple_linear_regression_data.csv")
X = df.iloc[:,:-1].values
y = df.iloc[:,-1].values
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=2,random_state=42)

In [9]:
class M_LR():
  def __init__(self):
    self.coef_=None
    self.intercept_=None
  def fit(self,X_train,y_train):
    X_train=np.insert(X_train,0,1,axis=1)
    bitas = np.linalg.inv(np.dot(X_train.T,X_train)).dot(X_train.T).dot(y_train)
    self.intercept_ = bitas[0]
    self.coef_ = bitas[1:]
  def predict(self,X_test):
    y_pred = np.dot(X_test,self.coef_) + self.intercept_
    return y_pred
  
lr = M_LR()
lr.fit(X_train,y_train)
lr.predict(X_test)

array([10.33921328,  8.29641491])

In [10]:
lr.coef_, lr.intercept_

(array([0.1350936 , 0.20601037, 0.03654884]), np.float64(2.870113695416464))

In [11]:
sk = LinearRegression()
sk.fit(X_train, y_train)
sk.predict(X_test)

array([10.33921328,  8.29641491])

In [12]:
sk.coef_, sk.intercept_

(array([0.1350936 , 0.20601037, 0.03654884]), np.float64(2.870113695416321))

<code>Polynomial Linear Regression</code>
<pre>It is use when our data is not linear it take degree as a parameter and convert our data base on degree</pre>

In [18]:
from sklearn.preprocessing import PolynomialFeatures
poly = PolynomialFeatures(degree=2)
X_poly = poly.fit_transform(X_train)
pd.DataFrame(X_poly, columns=poly.get_feature_names_out())

1     x0    x1     x2      x0^2     x0 x1      x0 x2     x1^2  \
0    1.0  22.85  6.76  86.90  522.1225  154.4660  1985.6650  45.6976   
1    1.0  12.17  8.62  92.58  148.1089  104.9054  1126.6986  74.3044   
2    1.0  20.43  8.91  93.80  417.3849  182.0313  1916.3340  79.3881   
3    1.0   8.41  5.90  90.31   70.7281   49.6190   759.5071  34.8100   
4    1.0  10.62  7.99  97.66  112.7844   84.8538  1037.1492  63.8401   
..   ...    ...   ...    ...       ...       ...        ...      ...   
143  1.0   8.97  7.49  60.73   80.4609   67.1853   544.7481  56.1001   
144  1.0  13.21  8.78  75.57  174.5041  115.9838   998.2797  77.0884   
145  1.0   8.64  5.82  93.44   74.6496   50.2848   807.3216  33.8724   
146  1.0  20.22  8.70  74.88  408.8484  175.9140  1514.0736  75.6900   
147  1.0  11.29  8.48  80.21  127.4641   95.7392   905.5709  71.9104   

        x1 x2       x2^2  
0    587.4440  7551.6100  
1    798.0396  8571.0564  
2    835.7580  8798.4400  
3    532.8290  8155.8961  
4    780.3034  9537.4756  
..        ...        ...  
143  454.8677  3688.1329  
144  663.5046  5710.8249  
145  543.8208  8731.0336  
146  651.4560  5607.0144  
147  680.1808  6433.6441  

[148 rows x 10 columns]