In [13]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split

<code>Simplest Linear Regression Implementation</code>

In [44]:

df = pd.read_csv('./Data/simple_linear_regression_data.csv')
X = df.iloc[:, 1].values.reshape(-1, 1)
y = df.iloc[:, 0].values
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [ ]:

class S_LR():
  def __init__(self):
    self.m = None
    self.b = None
  def fit(self,X_train,y_train):
    num = 0
    den = 0
    for i in range(X_train.shape[0]):

      num += (((X_train[i] - X_train.mean())*(y_train[i] - y_train.mean())))
      den += (((X_train[i] - X_train.mean())*(X_train[i] - X_train.mean())))
    
      self.m = num/den
      self.b = y_train.mean() - self.m * X_train.mean()
  def predict(self,X_test):
    return self.m * X_test + self.b
  
lr = S_LR()
lr.fit(X_train, y_train)
lr.predict(X_test)

array([3.27226494, 3.14764285, 2.39991033, 3.62536085, 4.26924163,
       3.39688702, 5.97241015, 3.52150911, 9.42028788, 8.7764071 ,
       9.66953206])

In [16]:
lr.m.item(),lr.b.item()

(2.0770347788051216, -10.602327384584253)

In [17]:
from sklearn.linear_model import LinearRegression
sk = LinearRegression()
sk.fit(X_train, y_train)
sk.predict(X_test)

array([3.27226494, 3.14764285, 2.39991033, 3.62536085, 4.26924163,
       3.39688702, 5.97241015, 3.52150911, 9.42028788, 8.7764071 ,
       9.66953206])

In [18]:
sk.coef_.item(), sk.intercept_.item()

(2.0770347788051198, -10.602327384584239)

<code>Multiple Linear Regression Implementation</code>

In [70]:
df = pd.read_csv("./Data/multiple_linear_regression_data.csv")
X = df.iloc[:,:-1].values
y = df.iloc[:,-1].values
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=2,random_state=42)

In [74]:
class M_LR():
  def __init__(self):
    self.coef_=None
    self.intercept_=None
  def fit(self,X_train,y_train):
    X_train=np.insert(X_train,0,1,axis=1)
    bitas = np.linalg.inv(np.dot(X_train.T,X_train)).dot(X_train.T).dot(y_train)
    self.intercept_ = bitas[0]
    self.coef_ = bitas[1:]
  def predict(self,X_test):
    y_pred = np.dot(X_test,self.coef_) + self.intercept_
    return y_pred
  
lr = M_LR()
lr.fit(X_train,y_train)
lr.predict(X_test)

array([10.33921328,  8.29641491])

In [75]:
lr.coef_, lr.intercept_

(array([0.1350936 , 0.20601037, 0.03654884]), np.float64(2.870113695416464))

In [76]:
sk = LinearRegression()
sk.fit(X_train, y_train)
sk.predict(X_test)

array([10.33921328,  8.29641491])

In [77]:
sk.coef_, sk.intercept_

(array([0.1350936 , 0.20601037, 0.03654884]), np.float64(2.870113695416321))